###
POST http://localhost:3333/test/a/b/c HTTP/1.1
content-type: application/json

{
    "args":[
        2,
        3
    ]
}

###
POST http://localhost:3333/test/foo2 HTTP/1.1
content-type: application/json

{
    "args":[
        3,
        4
    ]
}


###
POST http://localhost:3333/test/foo HTTP/1.1
content-type: application/json

{
    "args":[
        "tangoboy",
        "123456"
    ]
}


###
GET http://localhost:3333/test/foo?args[]=1&args[]={a:1} HTTP/1.1




###
POST http://localhost:3333/test/bar HTTP/1.1
content-type: application/json

{
    "args":[
        "tangoboy",
        "123456"
    ]
}



###

POST http://localhost:3333/aaa/index/foo HTTP/1.1
content-type: application/json

{
    "args":[
        "tangoboy",
        "123456"
    ]
}
